// <auto-generated />
using System;
using BHG.Platform.DemoServer.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BHG.Platform.DemoServer.Data.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190926051619_InitialAppDbMigration")]
    partial class InitialAppDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BHG.Platform.DemoServer.Data.Entities.LiuPengDistrict", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<int>("LiuPengRegionId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("LiuPengRegionId");

                    b.ToTable("LiuPengDistricts");
                });

            modelBuilder.Entity("BHG.Platform.DemoServer.Data.Entities.LiuPengLocation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ContactName")
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("LiuPengDistrictId");

                    b.Property<string>("ManagerName")
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ManagerPhone")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<int?>("PhysicalId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Printer")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Id");

                    b.HasIndex("LiuPengDistrictId");

                    b.ToTable("LiuPengLocations");
                });

            modelBuilder.Entity("BHG.Platform.DemoServer.Data.Entities.LiuPengRegion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("LiuPengRegions");
                });

            modelBuilder.Entity("BHG.Platform.DemoServer.Data.Entities.LiuPengDistrict", b =>
                {
                    b.HasOne("BHG.Platform.DemoServer.Data.Entities.LiuPengRegion")
                        .WithMany("LiuPengDistricts")
                        .HasForeignKey("LiuPengRegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BHG.Platform.DemoServer.Data.Entities.LiuPengLocation", b =>
                {
                    b.HasOne("BHG.Platform.DemoServer.Data.Entities.LiuPengDistrict")
                        .WithMany("LiuPengLocations")
                        .HasForeignKey("LiuPengDistrictId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
